server:
  port: 9003
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 182.92.232.148:9876
#          name-server: 192.168.100.42:9876




      bindings:
        myOutput:
          destination: login-user
          content-type: application/json


        myInput: # 通道名，对应代码中的消费监听组
          destination: login-user # exchange
          group: myInput   # 消费者组, 同组负载消费




